create table tb_transaction (id int8 generated by default as identity, date timestamp, desc varchar(255), value float8, client_id int8, primary key (id));
create table tb_user (id int8 generated by default as identity, confpass varchar(255), email varchar(255), name varchar(255), pass varchar(255), primary key (id));
alter table if exists tb_transaction add constraint FK8fgwrql22mduta03xl0ta2l10 foreign key (client_id) references tb_user;
